### ISSUE TITLE
Feature Request: Background Mode for desktop clients

### ISSUE THREAD

**Issue by Jayian1890** [ikus060/minarca#21] opened 2024-08-30 01:28 UTC
I've been using Minarca to keep my mac backed up remotely, I'd love if there was a feature to keep it running in the background/menu bar so it can be ran periodically without having to intervene directly. I prefer to backup daily, and this feature would make Minarca more beneficial.

**Comment by ikus060** [comment] 2024-08-30 12:03
Hello @Jayian1890,

Thanks for taking the time to report this feature request.

I'm not exactly sure to understand your request tough. Using Minarca, it's possible to configure a backup frequency so that you don't have to start the backup manually. When setting this feature, the backup is automatically start in the background at set intervals.

The reason for not keeping Minarca in the Task Menu at the bottom is mostly to reduce the resources footprint of the process. There is not a point to keep Minarca graphical interface running all the time.

But maybe I don't understand your request clearly. Don't hesitate to clarify.

Also, you may be interested into the next release that is currently distributed as a Beta version:
https://minarca.org/en_CA/blog/minarca-4/discover-the-beta-version-of-minarca-6-109

**Comment by Jayian1890** [comment] 2024-08-30 18:43
Using the macOS desktop client, the only way a backup can be initiated is by actively starting a backup, and the window has to be actively open the entire time. From what I can tell, there are no background functions. For example, I set the schedule to hourly, yet it hasn't started a backup since my initial one after setup. That's with or without the desktop app open.

**Comment by ikus060** [comment] 2024-08-30 19:03
> For example, I set the schedule to hourly, yet it hasn't started a backup since my initial one after setup.

This is not the expected behavior. When setting a backup interval, Minarca should wake-up every 15 min using launchd to check if it's time to make a backup. I know this is working on MacOS, I have a couple of client with it.

Could you send me the following elements ?

1. Verify the version you are running.
3.Check if this file exists: `/Users/myuser/Library/LaunchAgents/org.minarca.minarca-client.plist.plist` ? This is the configuration file created by Minarca.
4. Make sure the launchd service is running on your system: `ps -ax | grep launchd`
5. Verify if the configuration is properly picked by launchd by running: `launchctl list | grep org.minarca.minarca-client`
6. Finally, take a look at your minarca logs file to verify if there are not error.

**Comment by Jayian1890** [comment] 2024-08-31 05:54
launchd is running. The plist file doesn't exist, and launchctl command returns no results.

**Comment by ikus060** [comment] 2024-09-10 12:12
Hello @Jayian1890 

Sorry for the delay, I was in vacation last week.

> The plist file doesn't exist

This is the problem. The plist file is what trigger Minarca execution in background mode. If the file doesn't exists, then Minarca is never launched in background mode.

I'm not sure how you ended with this configuration. I will need to investigate.

Could you try to run the following command, 

```
/Applications/Minarca.app/Contents/MacOS/minarca schedule
```

That should repair the scheduler and create the missing plist file.

**Comment by ikus060** [comment] 2024-09-13 15:41
Hello @Jayian1890  Did you get a change to test ?

**Comment by ikus060** [comment] 2024-09-17 18:55
Will close this issue. Don't hesitate to re-open if you have more information.

**Closed by ikus060** 2024-09-17 18:55 UTC
