### ISSUE TITLE
Inactive link View my account online in the client application

### ISSUE THREAD

**Issue by satkas** [ikus060/minarca#15] opened 2023-07-03 20:06 UTC
At first (right after installing) the link worked. Now it doesn't want to move to browser bookmark
Debian 12, minarca 4.50 and 4.51

**Comment by ikus060** [comment] 2023-07-03 20:29
Hello @satkas 

Thank you for bringing this issue to our attention. We appreciate your effort in reporting it. To assist you effectively, could you please provide more details regarding the problem you encountered? Specifically, we would need the following information:

1. Steps to Reproduce: Please outline the exact steps you took when encountering the issue. This will help us recreate the problem on our end and better understand the root cause.

2. Expected Behavior: Describe what you expected to happen when you performed those steps. This will allow us to identify any discrepancies between the expected outcome and the actual behavior.

3. Current Behavior: Explain what is currently happening when you perform the steps. This will help us pinpoint the specific issue that needs to be addressed.

4. Running Platform: Let us know the platform or environment in which you encountered the problem. For instance, the operating system, browser, device, etc. This information can be crucial in understanding platform-specific issues.

5. Application Log: If possible, please share any relevant logs or error messages related to the issue. These logs can provide valuable insights into the problem and aid in the troubleshooting process.

Once we have these details, we'll be better equipped to investigate the matter further and work towards finding a resolution. Thank you for your cooperation, and we look forward to resolving this issue promptly.

**Comment by satkas** [comment] 2023-07-03 21:01
Client environment: Debian 12 Gnome , Web browser - Firefox ESR 102.12.0esr (64 bits), Opera opera-stable 100.0.4815.30

Steps to Reproduce: Standard launch of the client application by clicking on the icon
Expected Behavior:  After starting the client application, I want to open my account, copy preview in the browser (by clicking the View my account online link in the client application)

Current Behavior: By clicking the View my account online link in the client application, the application does not take me to the browser

**Comment by ikus060** [comment] 2023-11-24 18:21
@satkas Do you still experience this problem with the latest version ?

**Comment by satkas** [comment] 2023-11-26 10:45
Hi,
Yes, the problem is not solved (on Debian 12)
Some buttons work on the client, others don't. For example, clicking on the view my account link does not open the browser. All buttons in the Select files menu work. The Backup schedule is also fine. In the Restore menu, only full restore works. Partial restore doesn't work. In the Setting menu, Updates works, Notification does not work, and Disconnect the backup works.

**Comment by ikus060** [comment] 2023-11-26 19:36
ok, for buttons that doesn't "work" it should open a webbrowser. Did you check the log for any relevant error message ? or maybe the syslog ?

**Comment by ikus060** [comment] 2024-06-14 11:14
@satkas Could you check if you have the same issue with the Minarca Beta version recently roll out ?

Here how to download the client:
https://minarca.org/en_CA/beta

**Comment by ikus060** [comment] 2024-08-30 12:04
Closing. It should be fixed in beta version.

https://minarca.org/en_CA/blog/minarca-4/discover-the-beta-version-of-minarca-6-109

**Closed by ikus060** 2024-08-30 12:04 UTC
